"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { Icon } from "./auth-shell";
const API_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:5000/api";
const Field = ({ icon, children, action }: { icon: "mail" | "lock" | "user" | "phone" | "id"; children: React.ReactNode; action?: React.ReactNode }) => <div className="input-box"><Icon name={icon} />{children}{action}</div>;
const Divider = ({ children }: { children: string }) => <div className="divider"><span />{children}<span /></div>;
const SocialButtons = () => (
  <div className="social-buttons">
    <button type="button" onClick={() => alert("Login Google perlu konfigurasi OAuth.")}>
      <svg width="18" height="18" viewBox="0 0 24 24" style={{ marginRight: '8px', verticalAlign: 'middle' }}>
        <path fill="#4285F4" d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z" />
        <path fill="#34A853" d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" />
        <path fill="#FBBC05" d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.06H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.94l2.85-2.22.81-.63z" />
        <path fill="#EA4335" d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.06l3.66 2.84c.87-2.6 3.3-4.52 6.16-4.52z" />
      </svg>
      Google
    </button>
    <button type="button" onClick={() => alert("Login Facebook perlu konfigurasi OAuth.")}>
      <b className="facebook">f</b>Facebook
    </button>
  </div>
);
export function LoginForm() {
  const [role, setRole] = useState("WARGA"), [show, setShow] = useState(false), [message, setMessage] = useState(""), [loading, setLoading] = useState(false);
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setLoading(true); setMessage(""); const data = new FormData(e.currentTarget); const response = await fetch(API_URL + "/auth/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: data.get("email"), password: data.get("password"), remember: data.get("remember") === "on", role }) }); const result = await response.json(); setLoading(false); if (response.ok) { localStorage.setItem("rw_kita_user", JSON.stringify(result.user)); localStorage.setItem("rw_kita_token", result.token); window.location.href = "/portal"; } else setMessage(result.message); }
  return <><h2>Masuk ke Akun Anda</h2><p className="intro">Silakan lengkapi detail login untuk melanjutkan akses portal.</p><div className="auth-tabs"><button className="active">Masuk</button><Link href="/register">Daftar Baru</Link></div><form onSubmit={submit}><label>ALAMAT EMAIL</label><Field icon="mail"><input name="email" type="email" placeholder="nama@email.com" required /></Field><div className="label-row"><label>KATA SANDI</label><button type="button" className="text-link" onClick={() => alert("Silakan hubungi Admin RW untuk bantuan reset kata sandi.")}>Lupa Sandi?</button></div><Field icon="lock" action={<button className="password-toggle" type="button" onClick={() => setShow(!show)}><Icon name={show ? "eyeoff" : "eye"} /></button>}><input name="password" type={show ? "text" : "password"} placeholder="••••••••" required /></Field><label>SEBAGAI SIAPA?</label><div className="role-grid"><button type="button" onClick={() => setRole("WARGA")} className={role === "WARGA" ? "selected" : ""}><Icon name="user" /> Warga</button><button type="button" onClick={() => setRole("PENGURUS")} className={role === "PENGURUS" ? "selected" : ""}><Icon name="admin" /> Pengurus</button></div><label className="check-label"><input name="remember" type="checkbox" /> Ingat saya di perangkat ini</label>{message && <p className="form-message">{message}</p>}<button className="primary-button" disabled={loading}>{loading ? "Memproses..." : "Masuk ke Portal"}</button></form><Divider>ATAU MASUK DENGAN</Divider><SocialButtons /><p className="bottom-note">Butuh bantuan akses? <a href="mailto:admin@rwkita.id">Hubungi Admin RW</a></p></>;
}
export function RegisterForm() {
  const [role, setRole] = useState("WARGA"), [show, setShow] = useState(false), [message, setMessage] = useState(""), [loading, setLoading] = useState(false);
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const data = new FormData(e.currentTarget); if (data.get("password") !== data.get("confirmation")) return setMessage("Konfirmasi kata sandi belum sama."); setLoading(true); setMessage(""); const response = await fetch(API_URL + "/auth/register", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ fullName: data.get("fullName"), nik: data.get("nik"), email: data.get("email"), phone: data.get("phone"), password: data.get("password"), agreed: data.get("agreed") === "on", role }) }); const result = await response.json(); setLoading(false); if (response.ok) { localStorage.setItem("rw_kita_user", JSON.stringify(result.user)); localStorage.setItem("rw_kita_token", result.token); window.location.href = "/portal"; } else setMessage(result.message); }
  const password = (name: string, placeholder: string) => <Field icon="lock" action={<button className="password-toggle" type="button" onClick={() => setShow(!show)}><Icon name={show ? "eyeoff" : "eye"} /></button>}><input name={name} type={show ? "text" : "password"} placeholder={placeholder} minLength={8} required /></Field>;
  return <><h2>Buat Akun Baru</h2><p className="intro">Lengkapi data diri Anda untuk bergabung.</p><form onSubmit={submit} className="register-form"><label>Pilih Peran</label><div className="role-grid"><button type="button" onClick={() => setRole("WARGA")} className={role === "WARGA" ? "selected" : ""}>Warga</button><button type="button" onClick={() => setRole("PENGURUS")} className={role === "PENGURUS" ? "selected" : ""}>Pengurus</button></div><label>Nama Lengkap</label><Field icon="user"><input name="fullName" placeholder="Masukkan nama lengkap sesuai KTP" required /></Field><label>Nomor Induk Kependudukan (NIK)</label><Field icon="id"><input name="nik" inputMode="numeric" pattern="[0-9]{16}" maxLength={16} placeholder="16 digit NIK" required /></Field><div className="two-fields"><div><label>Alamat Email</label><Field icon="mail"><input name="email" type="email" placeholder="contoh@email.com" required /></Field></div><div><label>Nomor WhatsApp</label><Field icon="phone"><input name="phone" type="tel" placeholder="08xxxxxxxxxx" required /></Field></div></div><label>Kata Sandi</label>{password("password", "Minimal 8 karakter")}<label>Konfirmasi Kata Sandi</label>{password("confirmation", "Ulangi kata sandi")}<label className="check-label agreement"><input name="agreed" type="checkbox" required /> Saya menyetujui <a href="#">Syarat & Ketentuan</a> serta <a href="#">Kebijakan Privasi</a> yang berlaku.</label>{message && <p className="form-message">{message}</p>}<button className="primary-button" disabled={loading}>{loading ? "Memproses..." : "Daftar Sekarang  →"}</button></form><Divider>atau daftar dengan</Divider><SocialButtons /><p className="bottom-note">Sudah punya akun? <Link href="/login">Masuk di sini</Link></p></>;
}
